{"name": "test_update_post[NoValid - Post not found]", "status": "failed", "statusDetails": {"message": "Failed: [ERROR] Invalid id from Excel: 'None'", "trace": "self = <tests.test_api_users.TestPostsAPI object at 0x000002148CC016D0>, data = {'action': 'update', 'body': 'new', 'expected': False, 'id': 9999.0, ...}\n\n    @allure.description(\"Updates user details by user ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update\", parametrize=True))\n    def test_update_post(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n>           id = extract_post_id(data, fallback_id=self.__class__.created_ids[0])\nE           NameError: name 'extract_post_id' is not defined\n\ntests\\test_api_users.py:41: NameError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test_api_users.TestPostsAPI object at 0x000002148CC016D0>, data = {'action': 'update', 'body': 'new', 'expected': False, 'id': 9999.0, ...}\n\n    @allure.description(\"Updates user details by user ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update\", parametrize=True))\n    def test_update_post(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n            id = extract_post_id(data, fallback_id=self.__class__.created_ids[0])\n        except Exception:\n>           pytest.fail(f\"[ERROR] Invalid id from Excel: '{data.get('post_id')}'\")\nE           Failed: [ERROR] Invalid id from Excel: 'None'\n\ntests\\test_api_users.py:43: Failed"}, "description": "Updates user details by user ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "b2e0efb9-0a8c-47f1-98b2-21043984a45b-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "a384f2a4-0065-46b9-bf49-7ef2d61d123b-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "dcd7b3af-4283-46a2-b81c-266be123efec-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update', 'id': 9999.0, 'body': 'new', 'id': 'new', 'title': 1.0, 'expected': False, 'note': 'NoValid - Post not found'}"}], "start": 1753200052905, "stop": 1753200052907, "uuid": "fc6a2412-6637-4cda-87b3-862f5766d1de", "historyId": "6182ebfc0250cdb8669819fe89c3b6ce", "testCaseId": "16130e9d55726e09524cf02a0fdf9edc", "fullName": "tests.test_api_users.TestPostsAPI#test_update_post", "labels": [{"name": "epic", "value": "posts API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_users"}, {"name": "subSuite", "value": "TestPostsAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "27916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_users"}]}