{"name": "test_update_post[NoValid - Post not found]", "status": "failed", "statusDetails": {"message": "Failed: [ERROR] Invalid id from Excel: '9999.0'", "trace": "self = <tests.test_api_users.TestPostsAPI object at 0x00000266FCBC15B0>, data = {'action': 'update', 'body': 'new', 'expected': False, 'id': 9999.0, ...}\n\n    @allure.description(\"Updates user details by user ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update\", parametrize=True))\n    def test_update_post(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n>           post_id = extract_post_id(data, fallback_id=self.__class__.created_ids[0])\nE           AttributeError: type object 'TestPostsAPI' has no attribute 'created_ids'\n\ntests\\test_api_users.py:42: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test_api_users.TestPostsAPI object at 0x00000266FCBC15B0>, data = {'action': 'update', 'body': 'new', 'expected': False, 'id': 9999.0, ...}\n\n    @allure.description(\"Updates user details by user ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update\", parametrize=True))\n    def test_update_post(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n            post_id = extract_post_id(data, fallback_id=self.__class__.created_ids[0])\n        except Exception:\n>           pytest.fail(f\"[ERROR] Invalid id from Excel: '{data.get('id')}'\")\nE           Failed: [ERROR] Invalid id from Excel: '9999.0'\n\ntests\\test_api_users.py:44: Failed"}, "description": "Updates user details by user ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "e5d8fa14-ae04-49c2-a920-dd36d2b11f1d-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "4bd8ca84-ac05-4c38-8b90-87e419835b7a-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "5fad317b-2683-4f83-93a0-dfe5e3a8851c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update', 'id': 9999.0, 'body': 'new', 'id': 'new', 'title': 'HALA', 'expected': False, 'note': 'NoValid - Post not found'}"}], "start": 1753214304900, "stop": 1753214304902, "uuid": "783d4221-bd8c-40dd-b83e-9692e85da47f", "historyId": "09d24ddfa10f36519b6f86e577346c51", "testCaseId": "16130e9d55726e09524cf02a0fdf9edc", "fullName": "tests.test_api_users.TestPostsAPI#test_update_post", "labels": [{"name": "epic", "value": "posts API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_users"}, {"name": "subSuite", "value": "TestPostsAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "7728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_users"}]}