{"name": "test_update_users[NO-Valid-Partial Update]", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 400/404, got 403", "trace": "self = <tests.test_api_resource.TestusersAPI object at 0x000002E0CF6C6B10>, data = {'action': 'update_by_id', 'additionalneeds': '', 'id': 0.0, 'checkin': NaT, ...}\n\n    @allure.description(\"Updates users details by users ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update_by_id\", parametrize=True))\n    def test_update_users(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        id = extract_id(data, fallback_id=self.__class__.created_ids[0])\n        payload = build_users_payload(data)\n    \n        print(\"\\n[UPDATE] users ID:\", id)\n        print(\"[UPDATE] Payload:\", payload)\n    \n        res = self.users_api.update_users(id, payload=payload)\n    \n        print(\"[UPDATE] Response Code:\", res.status_code)\n        print(\"[UPDATE] Response Body:\", res.text)\n    \n>       validate_response(res, expected)\n\ntests\\test_api_resource.py:65: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nres = <Response [403]>, expected = False\n\n    def validate_response(res, expected):\n        \"\"\"\n        Validates the HTTP response status and JSON fields for single-object responses.\n        \"\"\"\n        if expected:\n            assert res.status_code in [200, 201, 204], f\"Expected 200/201/204, got {res.status_code}\"\n            if res.status_code == 204:\n                return\n            try:\n                data = res.json()\n            except Exception as e:\n                raise AssertionError(f\"Response is not valid JSON: {e}\")\n            assert_common_fields(data)\n        else:\n>           assert res.status_code in [400, 404,405], f\"Expected 400/404, got {res.status_code}\"\nE           AssertionError: Expected 400/404, got 403\n\nutils\\response_validators.py:47: AssertionError"}, "description": "Updates users details by users ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "3cca80d0-c882-4e6e-a97c-8a79f8ebffae-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "afa0bc50-cede-4012-b3f3-27b851eeb177-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "9b3f7999-5cfb-4a71-b343-bb36aa0ded13-attachment.txt", "type": "text/plain"}, {"name": "[PUT] request", "source": "d8895193-f501-49ac-8fa4-554876e8896a-attachment.txt", "type": "text/plain"}, {"name": "response [403]", "source": "47092e36-700e-44a9-8e2e-c80d351678bd-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update_by_id', 'id': 0.0, 'username': '', 'password': '', 'firstname': '', 'lastname': '', 'totalprice': '', 'depositpaid': '', 'checkin': NaT, 'checkout': NaT, 'additionalneeds': '', 'expected': False, 'note': 'NO-Valid-Partial Update'}"}], "start": 1753307616526, "stop": 1753307617135, "uuid": "2ff4d1a6-cc3b-4681-8ffc-5a376cdf2ab2", "historyId": "fa9d83b44863e1a5e416b26ce35507c2", "testCaseId": "b5cf996acdbf337d70d6630e3e1a8d62", "fullName": "tests.test_api_resource.TestusersAPI#test_update_users", "labels": [{"name": "epic", "value": "users API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_resource"}, {"name": "subSuite", "value": "TestusersAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "14940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_resource"}]}