{"name": "test_update_users[Valid-Update Full Data]", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <tests.test_api_resource.TestusersAPI object at 0x000001FBFFFAE9E0>, data = {'action': 'update_by_id', 'email': 'YOSSI@GMAIL.COM', 'expected': True, 'gender': 'male', ...}\n\n        @allure.description(\"Updates users details by users ID.\")\n        @pytest.mark.parametrize(*load_test_data(\"apis\", \"update_by_id\", parametrize=True))\n        def test_update_users(self, data):\n            expected = parse_bool(data.get(\"expected\"))\n    #◊û◊ï◊¶◊ô◊ê◊î ◊ê◊™ ◊î÷æid ◊û◊î◊û◊ô◊ú◊ï◊ü data, ◊ï◊ê◊ù ◊î◊ï◊ê ◊ú◊ê ◊ß◊ô◊ô◊ù ◊ê◊ï ◊®◊ô◊ß ‚Äì ◊î◊ô◊ê ◊û◊©◊™◊û◊©◊™ ◊ë◊û◊ñ◊î◊î ◊î◊®◊ê◊©◊ï◊ü ◊©◊†◊©◊û◊® ◊ë◊®◊©◊ô◊û◊™ created_ids ◊©◊ú ◊î◊û◊ó◊ú◊ß◊î ◊ë◊™◊ï◊® ◊¢◊®◊ö ◊ë◊®◊ô◊®◊™ ◊û◊ó◊ì◊ú.\n>           id = extract_id(data, fallback_id=self.__class__.created_ids[0])\nE           IndexError: list index out of range\n\ntests\\test_api_resource.py:46: IndexError"}, "description": "Updates users details by users ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "da849c93-dbe4-480b-8915-1277e6f8c6fb-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "7b7b2bcd-8b67-43e4-b1e7-1aa6cd357a6d-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "45bdfef3-2549-40d3-b71d-9deaf06f25b7-attachment.txt", "type": "text/plain"}, {"name": "[None] request", "source": "7d0517aa-ae25-4c66-a792-c4bca5826119-attachment.txt", "type": "text/plain"}, {"name": "Allure Attachment Error", "source": "1c64c41b-c4c4-4a98-ab53-573e4871f5ff-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update_by_id', 'id': '', 'name': 'UPDATED_NAME', 'email': 'YOSSI@GMAIL.COM', 'gender': 'male', 'status': 'active', 'expected': True, 'note': 'Valid-Update Full Data'}"}], "start": 1753358765567, "stop": 1753358765569, "uuid": "28640ed7-40b2-4a88-9429-cb9182e407f0", "historyId": "0c68cccc2511777797ef9758000ec33b", "testCaseId": "606f5d6c173cdf14acb8881bab7fb526", "fullName": "tests.test_api_resource.TestusersAPI#test_update_users", "labels": [{"name": "epic", "value": "users API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_resource"}, {"name": "subSuite", "value": "TestusersAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "21252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_resource"}]}