{"name": "test_update_users[Valid-Update Full Data]", "status": "failed", "statusDetails": {"message": "Failed: [ERROR] Invalid book_id from Excel: 'None'", "trace": "self = <tests.test_api_users.TestusersAPI object at 0x000001D6C36AD150>, data = {'action': 'update_by_id', 'author': 'Updated Name', 'book_id': '', 'expected': True, ...}\n\n    @allure.description(\"Updates users details by users ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update_by_id\", parametrize=True))\n    def test_update_users(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n>           book_id = extract_book_id(data, fallback_id=self.__class__.created_ids[0])\nE           IndexError: list index out of range\n\ntests\\test_api_users.py:45: IndexError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test_api_users.TestusersAPI object at 0x000001D6C36AD150>, data = {'action': 'update_by_id', 'author': 'Updated Name', 'book_id': '', 'expected': True, ...}\n\n    @allure.description(\"Updates users details by users ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update_by_id\", parametrize=True))\n    def test_update_users(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n            book_id = extract_book_id(data, fallback_id=self.__class__.created_ids[0])\n        except Exception:\n>           pytest.fail(f\"[ERROR] Invalid book_id from Excel: '{data.get('book_id')}'\")\nE           Failed: [ERROR] Invalid book_id from Excel: 'None'\n\ntests\\test_api_users.py:47: Failed"}, "description": "Updates users details by users ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "12ee70ad-954f-4666-84e5-8afade87a4b7-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "6c9a28f7-1853-40e8-a111-dc50b08f970d-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "682646f2-4efd-4766-8815-d0f7b09178e5-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update_by_id', 'book_id': '', 'author': 'Updated Name', 'is_borrowed': 1.0, 'title': 'Updated Title', 'user': 'alice', 'expected': True, 'note': 'Valid-Update Full Data'}"}], "start": 1753271377145, "stop": 1753271377146, "uuid": "408078fe-f339-4324-b0fb-82f29a801359", "historyId": "7226adadab9540ee68aab4e65dd5393c", "testCaseId": "e775056b77608a21e6a8495ae6ec9ca4", "fullName": "tests.test_api_users.TestusersAPI#test_update_users", "labels": [{"name": "epic", "value": "users API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_users"}, {"name": "subSuite", "value": "TestusersAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "19708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_users"}]}