{"name": "test_update_users[Valid-Update Full Data]", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <tests.test_api_resource.TestusersAPI object at 0x000002540DE0F820>, data = {'action': 'update_by_id', 'additionalneeds': 'Breakfast', 'id': '', 'checkin': Timestamp('2018-01-01 00:00:00'), ...}\n\n        @allure.description(\"Updates users details by users ID.\")\n        @pytest.mark.parametrize(*load_test_data(\"apis\", \"update_by_id\", parametrize=True))\n        def test_update_users(self, data):\n            expected = parse_bool(data.get(\"expected\"))\n    #◊û◊ï◊¶◊ô◊ê◊î ◊ê◊™ ◊î÷æresource_id ◊û◊î◊û◊ô◊ú◊ï◊ü data, ◊ï◊ê◊ù ◊î◊ï◊ê ◊ú◊ê ◊ß◊ô◊ô◊ù ◊ê◊ï ◊®◊ô◊ß ‚Äì ◊î◊ô◊ê ◊û◊©◊™◊û◊©◊™ ◊ë◊û◊ñ◊î◊î ◊î◊®◊ê◊©◊ï◊ü ◊©◊†◊©◊û◊® ◊ë◊®◊©◊ô◊û◊™ created_ids ◊©◊ú ◊î◊û◊ó◊ú◊ß◊î ◊ë◊™◊ï◊® ◊¢◊®◊ö ◊ë◊®◊ô◊®◊™ ◊û◊ó◊ì◊ú.\n>           resource_id = extract_id(data, fallback_id=self.__class__.created_ids[0])\nE           IndexError: list index out of range\n\ntests\\test_api_resource.py:46: IndexError"}, "description": "Updates users details by users ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "080e81c5-84c8-41e6-b0d2-3860ea3dd904-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "0a9a89fb-7831-4ff4-b021-228a355f756f-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "db29f59a-0404-4a47-87f8-b5d6d2a034a5-attachment.txt", "type": "text/plain"}, {"name": "[POST] request", "source": "a350a533-6cd3-486a-9b82-5cf5e4b3c102-attachment.txt", "type": "text/plain"}, {"name": "response [200]", "source": "6d3c71a6-4d65-4d42-a637-2b56876887dc-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update_by_id', 'id': '', 'username': '', 'password': '', 'firstname': 'dfdfbdfb', 'lastname': 'dffvfv', 'totalprice': 587.0, 'depositpaid': 1.0, 'checkin': Timestamp('2018-01-01 00:00:00'), 'checkout': Timestamp('2015-01-01 00:00:00'), 'additionalneeds': 'Breakfast', 'expected': True, 'note': 'Valid-Update Full Data'}"}], "start": 1753348031847, "stop": 1753348031851, "uuid": "269728a1-6047-4335-abe6-c21ec2dc6d7c", "historyId": "db577702e7d5876f39d83e1cae713839", "testCaseId": "b5cf996acdbf337d70d6630e3e1a8d62", "fullName": "tests.test_api_resource.TestusersAPI#test_update_users", "labels": [{"name": "epic", "value": "users API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_resource"}, {"name": "subSuite", "value": "TestusersAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "16060-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_resource"}]}