{"name": "test_update_post[NoValid - Post not found]", "status": "failed", "statusDetails": {"message": "Failed: [ERROR] Invalid id from Excel: 'None'", "trace": "self = <tests.test_api_users.TestPostsAPI object at 0x000001E6CD7A1370>, data = {'action': 'update', 'body': 'new', 'expected': False, 'id': 9999.0, ...}\n\n    @allure.description(\"Updates user details by user ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update\", parametrize=True))\n    def test_update_post(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n>           post_id = extract_post_id(data, fallback_id=self.__class__.created_ids[0])\nE           IndexError: list index out of range\n\ntests\\test_api_users.py:42: IndexError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test_api_users.TestPostsAPI object at 0x000001E6CD7A1370>, data = {'action': 'update', 'body': 'new', 'expected': False, 'id': 9999.0, ...}\n\n    @allure.description(\"Updates user details by user ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update\", parametrize=True))\n    def test_update_post(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n            post_id = extract_post_id(data, fallback_id=self.__class__.created_ids[0])\n        except Exception:\n>           pytest.fail(f\"[ERROR] Invalid id from Excel: '{data.get('post_id')}'\")\nE           Failed: [ERROR] Invalid id from Excel: 'None'\n\ntests\\test_api_users.py:44: Failed"}, "description": "Updates user details by user ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "222f8b51-dcbc-4ed7-9eb7-8e2623f71b1e-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "41cc3d5b-5135-4c3c-a8ff-e4abe44b9cc5-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "ea11c4bb-3ec8-4352-980f-8553024b4ae9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update', 'id': 9999.0, 'body': 'new', 'id': 'new', 'title': 1.0, 'expected': False, 'note': 'NoValid - Post not found'}"}], "start": 1753213311814, "stop": 1753213311816, "uuid": "ea0fa073-3d4c-451b-803d-636d6deb07b2", "historyId": "6182ebfc0250cdb8669819fe89c3b6ce", "testCaseId": "16130e9d55726e09524cf02a0fdf9edc", "fullName": "tests.test_api_users.TestPostsAPI#test_update_post", "labels": [{"name": "epic", "value": "posts API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_users"}, {"name": "subSuite", "value": "TestPostsAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "31768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_users"}]}