{"name": "test_update_users[NoValid- Book not found]", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <tests.test_api_resource.TestusersAPI object at 0x000002540DF91FD0>, data = {'action': 'update_by_id', 'additionalneeds': '', 'id': 999999.0, 'checkin': NaT, ...}\n\n        @allure.description(\"Updates users details by users ID.\")\n        @pytest.mark.parametrize(*load_test_data(\"apis\", \"update_by_id\", parametrize=True))\n        def test_update_users(self, data):\n            expected = parse_bool(data.get(\"expected\"))\n    #◊û◊ï◊¶◊ô◊ê◊î ◊ê◊™ ◊î÷æresource_id ◊û◊î◊û◊ô◊ú◊ï◊ü data, ◊ï◊ê◊ù ◊î◊ï◊ê ◊ú◊ê ◊ß◊ô◊ô◊ù ◊ê◊ï ◊®◊ô◊ß ‚Äì ◊î◊ô◊ê ◊û◊©◊™◊û◊©◊™ ◊ë◊û◊ñ◊î◊î ◊î◊®◊ê◊©◊ï◊ü ◊©◊†◊©◊û◊® ◊ë◊®◊©◊ô◊û◊™ created_ids ◊©◊ú ◊î◊û◊ó◊ú◊ß◊î ◊ë◊™◊ï◊® ◊¢◊®◊ö ◊ë◊®◊ô◊®◊™ ◊û◊ó◊ì◊ú.\n>           resource_id = extract_id(data, fallback_id=self.__class__.created_ids[0])\nE           IndexError: list index out of range\n\ntests\\test_api_resource.py:46: IndexError"}, "description": "Updates users details by users ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "1fd1a2ae-3b78-4b0d-8039-aae4d73ebf57-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "09788bc1-5f4b-46b3-9a46-52079ff36d3a-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "5b9f3f9f-fd7a-4f33-89a4-46295a570eb6-attachment.txt", "type": "text/plain"}, {"name": "[POST] request", "source": "7be5d9a8-7300-492b-aa58-a5cc820c3532-attachment.txt", "type": "text/plain"}, {"name": "response [200]", "source": "6bb02c44-b17c-48d0-a33d-1bf856578943-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update_by_id', 'id': 999999.0, 'username': '', 'password': '', 'firstname': '', 'lastname': '', 'totalprice': '', 'depositpaid': '', 'checkin': NaT, 'checkout': NaT, 'additionalneeds': '', 'expected': False, 'note': 'NoValid- Book not found'}"}], "start": 1753348033102, "stop": 1753348033126, "uuid": "69c940fa-8e28-46ce-aa13-6621d8ac541e", "historyId": "f0b01e43e31555aab78548d89af5e0bb", "testCaseId": "b5cf996acdbf337d70d6630e3e1a8d62", "fullName": "tests.test_api_resource.TestusersAPI#test_update_users", "labels": [{"name": "epic", "value": "users API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_resource"}, {"name": "subSuite", "value": "TestusersAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "16060-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_resource"}]}